// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241216124639_NewLocationsFields")]
    partial class NewLocationsFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApi.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowBulkPick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapacityUom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CycleCountClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FifoDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<double?>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PickingFlow")
                        .HasColumnType("REAL");

                    b.Property<string>("ReplenishmentLocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StoredQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Width")
                        .HasColumnType("REAL");

                    b.Property<double?>("XCoordinate")
                        .HasColumnType("REAL");

                    b.Property<double?>("YCoordinate")
                        .HasColumnType("REAL");

                    b.Property<double?>("ZCoordinate")
                        .HasColumnType("REAL");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
